### ISSUE TITLE
Can't Login

### ISSUE THREAD

**Issue by k-0-i** [cytopia/docker-dvwa#38]
## Start
``` 
make start
```

But ,MySQL don't have data.And it's empty
![image](https://github.com/cytopia/docker-dvwa/assets/95953449/c67c6d47-c70a-4552-a09f-e480df2293d7)

**Comment by fantomcheg** [comment]
The same problem

**Comment by alejng** [comment]
Same issue here

**Comment by paulchambaz** [comment]
Same issue here, if there is anything I can do to help let me know.

**Comment by tolfsh** [comment]
Hi! I got the same problem I think, I got the login page but nothing happen if I try any creds even if I run setup.php.
I tried to lower the PHP version to 7.1 and it worked, so maybe PHP 8.1 is not compatible with the code... Try to use older version of PHP by changing the tag as explained in the doc.

**Comment by AlrikRr** [comment]
Yes, can confirm its working fine if you change the PHP version to 7.1 ! Thanks @tolfsh

**Comment by ashpect** [comment]
Im building upon the k8s setup, and bumped down the image in deployment-dvwa.yaml image php-7.1 s. It howed these 
<img width="1315" alt="Screenshot 2024-09-03 at 12 57 59 PM" src="https://github.com/user-attachments/assets/78433e4d-cb7f-44ef-ad0e-35f50db56c6a">
errors on login page and after you try login using admin:password
<img width="1355" alt="Screenshot 2024-09-03 at 12 58 49 PM" src="https://github.com/user-attachments/assets/0c5f3637-f155-41c7-8b37-536bce7317bf">

**Comment by ashpect** [comment]
For future references : if you're directly building in k8s, something is breaking in the docker image, use this image until it's fixed : 
- vulnerables/web-dvwa (change contaner image in k8s/deployment-dvwa.yml)

I haven't tried to locally build and test it out. If I do, will keep you posted.

**Comment by Especial2x4** [comment]
it´s work with PHP 7.1

**Comment by n3r0-b1n4ry** [comment]
delete or comment line 102 in html/dvwa/includes/DBMS/MySQL.php
![image](https://github.com/user-attachments/assets/572b42a8-6a79-4ae8-b326-d4c5db395199)
and 
delete or comment line 14 to 20 in html/setup.php
![image](https://github.com/user-attachments/assets/746ca1bf-fcdb-4f0c-a06c-07ff39a8d536)

all issue will be fixed
